# .github/workflows/copy-release-to-pages.yml
name: Copy Release Assets to GitHub Pages

on:
  release:
    types: [published]  # 每当有新的 Release 发布时触发

permissions:
  contents: write       # 授予推送代码到 Pages 分支的权限

jobs:
  copy-assets:
    name: Copy Assets to Pages Branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the pages branch
        uses: actions/checkout@v4
        with:
          ref: 'main'  # 你的 Pages 分支是 main

      - name: Download Release Asset
        uses: robinraju/release-downloader@v1.8
        with:
          repository: ${{ github.repository }} # 当前仓库
          tag: ${{ github.event.release.tag_name }} # 当前 Release 的标签名
          fileName: "rs.glb" # 要下载的文件名
          out-file-path: "./glb/glb/" # 将文件下载并保存到这个路径下

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./       # 将当前目录的所有变更推送回去
          publish_branch: main  # 推送到 main 分支
          force_orphan: false   # 保留提交历史
